"""Add cascading delete for document embeddings and chat messages

Revision ID: 3701456a196a
Revises: 
Create Date: 2025-09-21 15:06:35.228068+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3701456a196a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_documents_file_hash'), 'documents', ['file_hash'], unique=False)
    op.drop_column('documents', 'tags')
    
    # Add cascading delete constraints
    # Drop existing foreign key constraints and recreate with CASCADE
    op.drop_constraint('document_embeddings_document_id_fkey', 'document_embeddings', type_='foreignkey')
    op.create_foreign_key('document_embeddings_document_id_fkey', 'document_embeddings', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    
    op.drop_constraint('chat_messages_session_id_fkey', 'chat_messages', type_='foreignkey')
    op.create_foreign_key('chat_messages_session_id_fkey', 'chat_messages', 'chat_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    
    op.drop_constraint('document_tags_document_id_fkey', 'document_tags', type_='foreignkey')
    op.create_foreign_key('document_tags_document_id_fkey', 'document_tags', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert cascading delete constraints back to original
    op.drop_constraint('document_tags_document_id_fkey', 'document_tags', type_='foreignkey')
    op.create_foreign_key('document_tags_document_id_fkey', 'document_tags', 'documents', ['document_id'], ['id'])
    
    op.drop_constraint('chat_messages_session_id_fkey', 'chat_messages', type_='foreignkey')
    op.create_foreign_key('chat_messages_session_id_fkey', 'chat_messages', 'chat_sessions', ['session_id'], ['id'])
    
    op.drop_constraint('document_embeddings_document_id_fkey', 'document_embeddings', type_='foreignkey')
    op.create_foreign_key('document_embeddings_document_id_fkey', 'document_embeddings', 'documents', ['document_id'], ['id'])
    
    op.add_column('documents', sa.Column('tags', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_documents_file_hash'), table_name='documents')
    # ### end Alembic commands ###
