"""add_property_entity_and_relationships

Revision ID: 6f2a99f2f397
Revises: 3701456a196a
Create Date: 2025-09-26 12:08:55.551393+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f2a99f2f397'
down_revision = '3701456a196a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chat_messages_session_id_fkey', 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'chat_sessions', ['session_id'], ['id'])
    op.add_column('chat_sessions', sa.Column('property_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chat_sessions', 'properties', ['property_id'], ['id'])
    op.drop_constraint('document_embeddings_document_id_fkey', 'document_embeddings', type_='foreignkey')
    op.create_foreign_key(None, 'document_embeddings', 'documents', ['document_id'], ['id'])
    op.drop_constraint('document_tags_document_id_fkey', 'document_tags', type_='foreignkey')
    op.create_foreign_key(None, 'document_tags', 'documents', ['document_id'], ['id'])
    op.add_column('documents', sa.Column('property_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'documents', 'properties', ['property_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'property_id')
    op.drop_constraint(None, 'document_tags', type_='foreignkey')
    op.create_foreign_key('document_tags_document_id_fkey', 'document_tags', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'document_embeddings', type_='foreignkey')
    op.create_foreign_key('document_embeddings_document_id_fkey', 'document_embeddings', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.drop_column('chat_sessions', 'property_id')
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key('chat_messages_session_id_fkey', 'chat_messages', 'chat_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
